<a href="https://colab.research.google.com/github/Shilpashree-S/PDA---23CSE313/blob/main/Numpy_Practice_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Sales Data Analysis

You have sales data for a store for 7 days: [250, 300, 150, 400, 350, 500, 450].

- Create a NumPy array from this data.

- Find total sales and average sales.

- Identify days where sales exceeded 350.

In [ ]:
# Create a Numpy array from this data.
sales_data = np.array([250, 300, 150, 400, 350, 500, 450])
print("Sales data: ",sales_data)

# Find total sale and average sales.
total_sales = np.sum(sales_data)
avg_sales = np.mean(sales_data)

print("Total sales: ",total_sales)
print("Average sales: ",avg_sales)

#Identify days where sales exceeded 350
print("Data of days where sales exceeded 350",sales_data[sales_data > 350])


Sales data:  [250 300 150 400 350 500 450]
Total sales:  2400
Average sales:  342.85714285714283
Data of days where sales exceeded 350 [400 500 450]


2. Temperature Matrix

You have a 2D array of daily temperatures for 3 cities over 5 days:

[[30, 32, 31, 29, 35],

 [25, 28, 27, 26, 30],

 [20, 22, 21, 23, 19]]


- Convert this into a NumPy array.

- Find the maximum temperature recorded in each city.

- Find the minimum temperature of each day across cities.

In [ ]:
# Convert this into a NumPy array.
temp_matrix = np.array([[30, 32, 31, 29, 35],

[25, 28, 27, 26, 30],

[20, 22, 21, 23, 19]])
print("Temperature Matrix: ", temp_matrix)

#Find the maximum temperature recorded in each city.
max_temp_across_city = temp_matrix.max(axis = 1)
print("Maximum temperature recorded in each city:",max_temp_across_city)

#Find the minimum temperature of each day across cities.
min_temp_each_day = temp_matrix.min(axis = 0)
print("Minimum temperature recorded each day across cities: ",min_temp_each_day)


Temperature Matrix:  [[30 32 31 29 35]
 [25 28 27 26 30]
 [20 22 21 23 19]]
Maximum temperature recorded in each city: [35 30 23]
Minimum temperature recorded each day across cities:  [20 22 21 23 19]


3.Image Pixel Manipulation

You are given a 5×5 grayscale image represented as integers 0–255.

- Create a 5×5 array filled with 128.

- Increase brightness by 50 using a scalar operation.

- Ensure the values do not exceed 255.

In [ ]:
# Create a 5×5 array filled with 128.
image_pix_array = np.full((5,5),128)
print("Initial Image pixel array:\n",image_pix_array)

# Increase brightness by 50 using a scalar operation.
bright_arr = image_pix_array + 50
print("Result after scalar addition: \n",bright_arr)

# Ensure the values do not exceed 255.
clipped_array = np.clip(bright_arr, 0, 255)
print("Clipped array:\n", clipped_array)

Initial Image pixel array:
 [[128 128 128 128 128]
 [128 128 128 128 128]
 [128 128 128 128 128]
 [128 128 128 128 128]
 [128 128 128 128 128]]
Result after scalar addition: 
 [[178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]]
Clipped array:
 [[178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]
 [178 178 178 178 178]]


Note:

The numpy.clip() function in Python is used to limit the values in a NumPy array to a specified range. It takes an array, a minimum value, and a maximum value as input. Any element in the array that is less than the minimum value will be replaced by the minimum value, and any element greater than the maximum value will be replaced by the maximum value.

Syntax:

numpy.clip(a, a_min, a_max, out=None)

4. Student Marks Adjustment

A class has marks [45, 78, 90, 66, 59].

- Create a NumPy array.

- Add 5 grace marks to students scoring below 60.

- Calculate the new average.

In [ ]:
# Create a NumPy array.
student_marks = np.array([45, 78, 90, 66, 59])
print("Student Marks:\n", student_marks)

# Add 5 grace marks to students scoring below 60.
student_marks[student_marks < 60] += 5
print("After adding grace marks:\n",student_marks)

# Calculate the new average.
new_avg_marks = student_marks.mean()
print("New Average Marks:",new_avg_marks)

Student Marks:
 [45 78 90 66 59]
After adding grace marks:
 [50 78 90 66 64]
New Average Marks: 69.6


5. Product Inventory

You have product quantities in two warehouses:

Warehouse A: [10, 20, 15]  
Warehouse B: [5, 15, 10]


- Represent these as 1D NumPy arrays.

- Compute total quantity for each product across warehouses using vectorized operations.

- Find which products have total quantity below 20.

In [ ]:
# Represent these as 1D NumPy arrays.
warehouse_A = np.array([10, 20, 15])
warehouse_B = np.array([5, 15, 10])
print("Warehouse A\n",warehouse_A)
print("Warehouse B\n",warehouse_B)

# Compute total quantity for each product across warehouses using vectorized operations.
total_qty = warehouse_A + warehouse_B
print("Total quantity for each product across warehouses:\n",total_qty)

# Find which products have total quantity below 20.
print("Products having total quantity below 20:\n",total_qty[total_qty < 20])

Warehouse A
 [10 20 15]
Warehouse B
 [ 5 15 10]
Total quantity for each product across warehouses:
 [15 35 25]
Products having total quantity below 20:
 [15]


6. Matrix Operations

- Create a 3×3 matrix with numbers 1–9.

- Compute the square of each element using ufunc.

- Compute the sum of each row.

- Subtract 5 from elements of the second column using in-place operations.

In [ ]:
# Create a 3×3 matrix with numbers 1–9.
mat = np.arange(1,10).reshape(3,3)
print("Original Array\n",mat)

# Compute the square of each element using ufunc.
squared_arr = np.square(mat)
print("Matrix after squaring:\n",squared_arr)

# Compute the sum of each row.
rowise_sum = np.sum(mat, axis = 1)
print("Sum of each row:", rowise_sum)

# Subtract 5 from elements of the second column using in-place operations.
mat[:,1] -= 5
print("After Subtraction:\n",mat)

Original Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after squaring:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Sum of each row: [ 6 15 24]
After Subtraction:
 [[ 1 -3  3]
 [ 4  0  6]
 [ 7  3  9]]


7. Weather Change Analysis

You have temperatures for two weeks (arrays of 7 elements each):

    Week1 = [32, 31, 30, 28, 29, 27, 33]
    Week2 = [33, 32, 28, 27, 31, 29, 35]
  - Find the day-wise temperature difference between the weeks.
  - Identify days where temperature increased.
  - Compute the average increase.

In [4]:
import numpy as np

Week1 = np.array([32, 31, 30, 28, 29, 27, 33])
Week2 = np.array([33, 32, 28, 27, 31, 29, 35])
print("Week 1:",Week1)
print("week 2:",Week2)
#Day-wise temperature difference
diff = Week2 - Week1
print("Daywise temperature difference:",diff)
# Identify days where temperature increased
increase_days = diff > 0
print("Boolean array showing the days with temperature increase:",increase_days)
#Compute the average increase
avg_increase = np.mean(diff[diff > 0])
print("Avg Increase in temperature",avg_increase)




Week 1: [32 31 30 28 29 27 33]
week 2: [33 32 28 27 31 29 35]
Daywise temperature difference: [ 1  1 -2 -1  2  2  2]
Boolean array showing the days with temperature increase: [ True  True False False  True  True  True]
Avg Increase in temperature 1.6


8. 1D Array - Basic Indexing

Create an array a = [10, 20, 30, 40, 50].

Print:

  - first element

  - last element

  - element at index 2

In [5]:
arr = np.array([10, 20, 30, 40, 50])

#First Element
print("First Element:",arr[0])

#Last Element
print("Last Element: ",arr[-1])

#Element at index 2
print("Element at index 2: ",arr[2])

First Element: 10
Last Element:  50
Element at index 2:  30


9. 1D ARRAY – Negative Indexing

For a = np.array([5, 10, 15, 20, 25])

print:

- the last 3 elements using negative indices

- the second last element

In [9]:
a = np.array([5, 10, 15, 20, 25])
# The last 3 elements using negative indices
print("Last 3 Elements:",a[-3:])
# The second last element
print("Second Last Element:",a[-2])

Last 3 Elements: [15 20 25]
Second Last Element: 20


10. 1D ARRAY – Basic Slicing


Create an array from 10 to 19 using np.arange().

Print:

  - Elements from index 3 to 7

  - First 5 elements

  - Alternate elements

In [11]:
arr = np.arange(10,19)
# Elements from index 3 to 7
print(arr[3:7])
# First 5 elements
print(arr[:5])
# Alternate elements
print(arr[::2])

[13 14 15 16]
[10 11 12 13 14]
[10 12 14 16 18]


11. 1D ARRAY – Slice with Steps


a = np.arange(0, 20, 2)

Extract:

  - every 2nd element

  - every 3rd element

  - slice from index 2 to index 7 with step = 2

In [ ]:
a = np.arange(0, 20, 2)

print(a[::2])        # every 2nd element
print(a[::3])        # every 3rd element
print(a[2:8:2])      # index 2 to 7 with step 2

12. 1D ARRAY – Fancy Indexing



a = np.array([11, 22, 33, 44, 55, 66])

Using fancy indexing, extract elements at positions 0, 3, and 5.

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66])

print(a[[0, 3, 5]]) # Elements at positions 0, 3, and 5



13. 2D ARRAY – Basic Indexing


Create a 2D array:

      [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]


Print:

- element at row 1, column 2

- element at last row, first column

- entire 2nd row

In [12]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[1, 2])     # row 1, col 2 → 6
print(A[-1, 0])    # last row, first col → 7
print(A[1, :])     # second row → [4 5 6]


6
7
[4 5 6]


14. 2D ARRAY – Column Access


Using the above matrix, print:

  - Entire first column

  - Entire third column

In [13]:
print(A[:, 0])     # first column → [1 4 7]
print(A[:, 2])     # third column → [3 6 9]

[1 4 7]
[3 6 9]


15. 2D ARRAY – Row Slicing


Given

A = [[10, 20, 30],
     [40, 50, 60],
     [70, 80, 90],
     [100,110,120]]


Extract:

  - First 2 rows

  - Last 2 rows

  - Rows 1 to 3

In [14]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100,110,120]
])

print(A[0:2])      # first 2 rows
print(A[2:4])      # last 2 rows
print(A[1:3])      # rows 1 to 2


[[10 20 30]
 [40 50 60]]
[[ 70  80  90]
 [100 110 120]]
[[40 50 60]
 [70 80 90]]


16. 2D ARRAY – Submatrix Extraction (Core Skill)


Given

    B = np.arange(1, 17).reshape(4, 4)


Extract the following submatrices:

  - top-left 2×2

  - top-right 2×2

  - bottom-left 2×2

  - center 2×2

In [ ]:
B = np.arange(1, 17).reshape(4, 4)

# 1. top-left 2x2
print(B[0:2, 0:2])

# 2. top-right 2x2
print(B[0:2, 2:4])

# 3. bottom-left 2x2
print(B[2:4, 0:2])

# 4. center 2x2 (rows 1–2, cols 1–2)
print(B[1:3, 1:3])


17. 2D ARRAY – Non-Contiguous Row/Column Selection


Given the matrix B, extract:

  - Rows 0 and 2

  - Columns 1 and 3

  - Rows 0 & 3 and columns 0 & 2 (combined fancy indexing + slicing)

In [15]:
B = np.arange(1, 17).reshape(4, 4)

print(B[[0, 2], :])        # rows 0 and 2
print(B[:, [1, 3]])        # columns 1 and 3
print(B[[0, 3], :][:, [0, 2]])  # rows 0 & 3, cols 0 & 2


[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 1  3]
 [13 15]]


18. 2D ARRAY – Complex Slicing


    C = np.arange(1, 26).reshape(5, 5)

Perform the following slices:

  - Extract every alternate row

  - Extract every alternate column

  - Extract the diagonal slice C[1:4, 1:4]

  - Extract the checkerboard pattern:

In [ ]:
C = np.arange(1, 26).reshape(5, 5)

# 1. every alternate row
print(C[::2])

# 2. every alternate column
print(C[:, ::2])

# 3. center diagonal block (1:4, 1:4)
print(C[1:4, 1:4])

# 4. checkerboard pattern
print(C[::2, ::2])


19. Iteration Over Arrays
Sum of Elements Using Iteration (1D)

- Create a 1D NumPy array of 10 integers.
- Without using NumPy’s built-in sum() function, use a for loop to compute the total.

In [16]:
import numpy as np

a = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
total = 0

for i in a:
    total += i

print("Sum:", total)


Sum: 275


20. Counting Positive, Negative, and Zero Values (1D)

Given an array of integers, iterate through it and count:

  - how many numbers are positive

  - how many are negative

  - how many are zero

  - Print all three counts.

In [17]:
a = np.array([3, -1, 0, 7, -9, 12, 0])

pos = neg = zero = 0

for i in a:
    if i > 0:
        pos += 1
    elif i < 0:
        neg += 1
    else:
        zero += 1

print("Positive:", pos)
print("Negative:", neg)
print("Zero:", zero)


Positive: 3
Negative: 2
Zero: 2


21. Reverse Print Using Iteration (1D)

  - Given a 1D array, print its elements in reverse order using a loop, not slicing.

In [18]:
a = np.array([10, 20, 30, 40, 50])

for i in range(len(a)-1, -1, -1):
    print(a[i])


50
40
30
20
10


22. Row-wise Printing With Row Numbers (2D)

Given a 4×4 matrix, print:

    Row 0: [...]
    Row 1: [...]
    Row 2: [...]
    Row 3: [...]


Use for row in A.

In [23]:
A = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100,110,120],
    [130,140,150,160]
])

i=0
for row in A:
    print(f"Row {i}:",row)
    i+=1


Row 0: [10 20 30 40]
Row 1: [50 60 70 80]
Row 2: [ 90 100 110 120]
Row 3: [130 140 150 160]


Note: Alternatively, we can use the below code using enumerate. enumerate() is a built-in Python function that lets you loop over a sequence and automatically get the index along with the value.


In [ ]:
import numpy as np

A = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100,110,120],
    [130,140,150,160]
])

for i, row in enumerate(A):
    print(f"Row {i}:", row)


23. Count Elements > 50 (2D)

- Given a 2D array (matrix of marks), iterate through each row, and for each row count how many elements are greater than 50.
- Print the row index and the count.

In [24]:
A = np.array([
    [10, 60, 30, 90],
    [40, 55, 80, 20],
    [75, 35, 95, 50]
])

for idx, row in enumerate(A):
    count = 0
    for value in row:
        if value > 50:
            count += 1
    print(f"Row {idx} has {count} elements > 50")


Row 0 has 2 elements > 50
Row 1 has 2 elements > 50
Row 2 has 2 elements > 50


24. Flatten and Find Maximum Using Iteration

Given a 2D array, use:

    for item in A.flat:
  - to find the maximum value without using NumPy’s max().

In [ ]:
A = np.array([
    [12, 45, 7],
    [88, 23, 56],
    [19, 31, 90]
])

max_val = A.flat[0]

for item in A.flat:
    if item > max_val:
        max_val = item

print("Maximum value:", max_val)


25. You are given the following 3×4 matrix:

            A = np.array([
                  [10, 20, 30, 40],
                  [5, 15, 45, 25],
                  [8, 18, 28, 38]
               ])


- Define a function that takes a 1D array (a row) and returns:

      max(row) – min(row)


- Use np.apply_along_axis() with axis=1 to compute the range of each row.

In [26]:
import numpy as np

A = np.array([
    [10, 20, 30, 40],
    [5, 15, 45, 25],
    [8, 18, 28,38]
])

def row_range(x):
    return x.max() - x.min()

result = np.apply_along_axis(row_range, axis=1, arr=A)
print(result)


[30 40 30]


26. Column-wise Product Using apply_along_axis()

Consider the following 2×4 matrix:

        A = np.array([
              [2, 3, 4, 5],
              [6, 7, 8, 9]
            ])



- Write a custom function that returns the product of all elements in a 1D vector.

- Use np.apply_along_axis() with axis=0 to compute the product of each column.

In [27]:
A = np.array([
    [2, 3, 4, 5],
    [6, 7, 8, 9]
])

def product(x):
    p = 1
    for i in x:
        p *= i
    return p

result = np.apply_along_axis(product, axis=0, arr=A)
print(result)


[12 21 32 45]


27. Normalize Each Row Using apply_along_axis()

You are given this 3×3 matrix of test scores:

      A = np.array([
           [50, 60, 70],
           [80, 85, 90],
           [40, 45, 55]
        ])



Write the following function:

      def normalize(x):
        return (x - x.mean()) / x.std()


- Use np.apply_along_axis() with axis=1 to normalize each row.

In [28]:
A = np.array([
     [50, 60, 70],
     [80, 85, 90],
     [40, 45, 55]
])

def normalize(x):
    return (x - x.mean()) / x.std()

result = np.apply_along_axis(normalize, axis=1, arr=A)
print(result)


[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.06904497 -0.26726124  1.33630621]]


28. Count Even Numbers in Each Column

You are given the following 3×4 matrix:

      A = np.array([
        [12, 15, 20, 33],
        [22, 35, 44, 55],
        [13, 66, 77, 88]
    ])



- Write a custom function that receives a 1D array (a column), counts how many values are even, and returns that count.

- Use:

      np.apply_along_axis(func, axis=0, arr=A)


to compute even counts for each column.

In [29]:
A = np.array([
    [12, 15, 20, 33],
    [22, 35, 44, 55],
    [13, 66, 77, 88]
])

def count_even(x):
    count = 0
    for i in x:
        if i % 2 == 0:
            count += 1
    return count

result = np.apply_along_axis(count_even, axis=0, arr=A)
print(result)


[2 1 2 1]


29. Convert Celsius to Fahrenheit Using apply_along_axis()

You are given this 3×3 temperature matrix in Celsius:

      temps = np.array([
          [0, 10, 20],
          [15, 25, 30],
          [5, 12, 18]
        ])



- Create a function:

        def to_fahrenheit(x):
          return (x * 9/5) + 32


- Apply it row-wise using np.apply_along_axis() to convert the entire matrix to Fahrenheit.

In [30]:
A = np.array([
    [0, 10, 20],
    [15, 25, 30],
    [5, 12, 18]
])

def to_fahrenheit(x):
    return (x * 9/5) + 32

result = np.apply_along_axis(to_fahrenheit, axis=1, arr=A)
print(result)


[[32.  50.  68. ]
 [59.  77.  86. ]
 [41.  53.6 64.4]]


30. Calculate the Median Deviation for Each Column

You are given the following 4×3 matrix representing daily measurements from three sensors:

      A = np.array([
          [12, 18, 25],
          [15, 20, 22],
          [14, 19, 28],
          [16, 21, 24]
      ])



- Define a custom function that takes a 1D array (a column) and returns:

      median deviation = median(column) - min(column)


- Use np.apply_along_axis() with axis=0 to compute the median deviation of each column.

- Print the resulting array.

In [31]:
import numpy as np

A = np.array([
    [12, 18, 25],
    [15, 20, 22],
    [14, 19, 28],
    [16, 21, 24]
])
def median_deviation(x):
    return np.median(x) - np.min(x)
result = np.apply_along_axis(median_deviation, axis=0, arr=A)
print(result)


[2.5 1.5 2.5]
